<?php
session_start();
if (!isset($_SESSION['doctor_id'])) {
    header("Location: doctor_login.php");
    exit();
}
include '../db.php';
$doctor_id = $_SESSION['doctor_id'];

// Fetch doctor name
$query = $conn->prepare("SELECT name FROM doctors WHERE id = ?");
$query->bind_param("i", $doctor_id);
$query->execute();
$query->bind_result($doctor_name);
$query->fetch();
$query->close();

$success = $error = '';

// Handle medical record generation
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $appointment_id = intval($_POST['appointment_id']);
    $diagnosis = trim($_POST['diagnosis']);
    $treatment = trim($_POST['treatment']);
    $prescription = trim($_POST['prescription']);
    $notes = trim($_POST['notes']);
    $file_path = '';
    
    // Validate inputs
    if ($appointment_id && !empty($diagnosis)) {
        // Check if appointment belongs to this doctor and is completed
        $check = $conn->prepare("SELECT a.id, a.patient_id, a.appointment_date, p.full_name 
                                FROM appointments a 
                                JOIN patients p ON a.patient_id = p.id 
                                WHERE a.id = ? AND a.doctor_id = ? AND a.status = 'Completed'");
        $check->bind_param("ii", $appointment_id, $doctor_id);
        $check->execute();
        $check->store_result();
        
        if ($check->num_rows > 0) {
            $check->bind_result($apt_id, $patient_id, $appointment_date, $patient_name);
            $check->fetch();
            
            // Handle file upload
            if (isset($_FILES['medical_file']) && $_FILES['medical_file']['error'] === UPLOAD_ERR_OK) {
                $upload_dir = '../uploads/medical_records/';
                if (!is_dir($upload_dir)) {
                    mkdir($upload_dir, 0777, true);
                }
                
                $file_info = pathinfo($_FILES['medical_file']['name']);
                $file_extension = strtolower($file_info['extension']);
                
                // Allow only specific file types
                $allowed_extensions = ['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'txt'];
                
                if (in_array($file_extension, $allowed_extensions)) {
                    $file_name = 'medical_record_' . $patient_id . '_' . time() . '.' . $file_extension;
                    $file_path = $upload_dir . $file_name;
                    
                    if (move_uploaded_file($_FILES['medical_file']['tmp_name'], $file_path)) {
                        $file_path = 'medical_records/' . $file_name;
                    } else {
                        $error = "Failed to upload file.";
                    }
                } else {
                    $error = "Invalid file type. Allowed: PDF, DOC, DOCX, JPG, PNG, TXT";
                }
            }
            
            if (empty($error)) {
                // Create comprehensive medical record description
                $description = "Patient: " . $patient_name . "\n";
                $description .= "Appointment Date: " . $appointment_date . "\n\n";
                $description .= "DIAGNOSIS:\n" . $diagnosis . "\n\n";
                
                if (!empty($treatment)) {
                    $description .= "TREATMENT PLAN:\n" . $treatment . "\n\n";
                }
                
                if (!empty($prescription)) {
                    $description .= "PRESCRIPTION:\n" . $prescription . "\n\n";
                }
                
                if (!empty($notes)) {
                    $description .= "ADDITIONAL NOTES:\n" . $notes . "\n\n";
                }
                
                $description .= "Generated by: Dr. " . $doctor_name . "\n";
                $description .= "Date: " . date('Y-m-d H:i:s');
                
                $stmt = $conn->prepare("INSERT INTO medical_records (patient_id, doctor_id, record_date, description, file) VALUES (?, ?, ?, ?, ?)");
                $stmt->bind_param("iisss", $patient_id, $doctor_id, $appointment_date, $description, $file_path);
                
                if ($stmt->execute()) {
                    $success = "Medical record generated successfully for " . $patient_name . "!";
                } else {
                    $error = "Failed to generate medical record.";
                }
                $stmt->close();
            }
        } else {
            $error = "Invalid appointment or appointment not completed.";
        }
        $check->close();
    } else {
        $error = "Please fill all required fields.";
    }
}

// Fetch completed appointments for this doctor
$completed_appointments = $conn->query("SELECT a.id, a.appointment_date, a.appointment_time, p.full_name, p.email 
                                       FROM appointments a 
                                       JOIN patients p ON a.patient_id = p.id 
                                       WHERE a.doctor_id = $doctor_id AND a.status = 'Completed' 
                                       ORDER BY a.appointment_date DESC, a.appointment_time DESC");
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generate Medical Record</title>
    <style>
        body {
            font-family: 'Segoe UI', sans-serif;
            background: linear-gradient(120deg, #f0f8ff 0%, #dff3ec 100%);
            margin: 0;
            padding: 0;
            min-height: 100vh;
        }
        
        .sidebar {
            width: 220px;
            height: 100vh;
            background: #2c3e50;
            padding: 20px;
            color: white;
            position: fixed;
            box-shadow: 2px 0 10px rgba(0,0,0,0.1);
        }
        
        .sidebar h2 {
            font-size: 22px;
            margin-bottom: 30px;
        }
        
        .sidebar a {
            color: white;
            display: block;
            margin: 10px 0;
            text-decoration: none;
            padding: 10px;
            border-radius: 6px;
        }
        
        .sidebar a:hover {
            background: #34495e;
        }
        
        .main {
            margin-left: 240px;
            padding: 30px;
        }
        
        .card {
            background: white;
            padding: 30px;
            border-radius: 15px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.08);
            max-width: 800px;
        }
        
        .card h3 {
            color: #0077b6;
            font-size: 20px;
            margin-bottom: 20px;
            font-weight: 600;
        }
        
        .form-section {
            margin-bottom: 25px;
        }
        
        .form-section h4 {
            color: #333;
            margin-bottom: 10px;
            font-size: 16px;
        }
        
        form label {
            display: block;
            margin-top: 15px;
            font-weight: bold;
            color: #333;
        }
        
        select, input[type="text"], textarea {
            width: 100%;
            padding: 12px;
            margin-top: 5px;
            border-radius: 8px;
            border: 1px solid #ddd;
            font-size: 16px;
            box-sizing: border-box;
        }
        
        textarea {
            height: 100px;
            resize: vertical;
        }
        
        input[type="file"] {
            padding: 10px;
            border: 2px dashed #ddd;
            border-radius: 8px;
            background: #f9f9f9;
        }
        
        button {
            margin-top: 20px;
            padding: 12px 25px;
            background: linear-gradient(135deg, #0077b6, #023e8a);
            color: white;
            border: none;
            border-radius: 8px;
            font-size: 16px;
            font-weight: 500;
            cursor: pointer;
            transition: all 0.3s ease;
        }
        
        button:hover {
            transform: translateY(-2px);
            box-shadow: 0 6px 20px rgba(0,119,182,0.3);
        }
        
        .success {
            background: #d1fae5;
            color: #065f46;
            padding: 15px;
            border-radius: 8px;
            margin-top: 15px;
            border-left: 4px solid #10b981;
        }
        
        .error {
            background: #fee2e2;
            color: #991b1b;
            padding: 15px;
            border-radius: 8px;
            margin-top: 15px;
            border-left: 4px solid #ef4444;
        }
        
        .logout {
            margin-top: 30px;
            display: inline-block;
            color: red;
            font-weight: bold;
        }
        
        .file-info {
            background: #e3f2fd;
            padding: 10px;
            border-radius: 6px;
            margin-top: 10px;
            font-size: 14px;
            color: #1976d2;
        }
        
        .appointment-info {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 8px;
            margin-top: 10px;
            border-left: 4px solid #0077b6;
        }
        
        .no-appointments {
            text-align: center;
            padding: 40px;
            color: #666;
        }
        
        .no-appointments-icon {
            font-size: 48px;
            margin-bottom: 15px;
        }
    </style>
</head>
<body>
<div class="sidebar">
    <h2>Doctor Dashboard</h2>
    <p>👨‍⚕️ <strong><?= htmlspecialchars($doctor_name) ?></strong></p>
    <a href="doctor_dashboard.php">🏠 Dashboard Home</a>
    <a href="view_appointments.php">📅 View Appointments</a>
    <a href="manage_availability.php">🗓️ Manage Availability</a>
    <a href="manage_appointment.php">🛠️ Manage Appointments</a>
    <a href="add_medical_record.php">🩺 Add Medical Record</a>
    <a href="generate_medical_record.php">📋 Generate Medical Record</a>
    <a href="view_medical_records.php">📋 My Medical Records</a>
    <a href="manage_account.php">⚙️ Manage Account</a>
    <a class="logout" href="../logout.php">🚪 Logout</a>
  </div>
    
    <div class="main">
        <div class="card">
            <h3>📋 Generate Medical Record from Completed Appointment</h3>
            
            <?php if ($success): ?>
                <div class="success"><?= $success ?></div>
            <?php endif; ?>
            
            <?php if ($error): ?>
                <div class="error"><?= $error ?></div>
            <?php endif; ?>
            
            <?php if ($completed_appointments->num_rows === 0): ?>
                <div class="no-appointments">
                    <div class="no-appointments-icon">📅</div>
                    <h4>No Completed Appointments</h4>
                    <p>You can generate medical records once you have completed appointments with patients.</p>
                </div>
            <?php else: ?>
                <form method="POST" enctype="multipart/form-data">
                    <div class="form-section">
                        <h4>📅 Select Completed Appointment</h4>
                        <label for="appointment_id">Choose Patient & Appointment:</label>
                        <select name="appointment_id" id="appointment_id" required>
                            <option value="">-- Select Completed Appointment --</option>
                            <?php while ($appointment = $completed_appointments->fetch_assoc()): ?>
                                <option value="<?= $appointment['id'] ?>">
                                    <?= htmlspecialchars($appointment['full_name']) ?> - 
                                    <?= date('M d, Y', strtotime($appointment['appointment_date'])) ?> 
                                    at <?= date('g:i A', strtotime($appointment['appointment_time'])) ?>
                                </option>
                            <?php endwhile; ?>
                        </select>
                    </div>
                    
                    <div class="form-section">
                        <h4>Medical Information</h4>
                        <label for="diagnosis">Diagnosis *</label>
                        <textarea name="diagnosis" id="diagnosis" placeholder="Enter patient diagnosis..." required></textarea>
                        <label for="treatment">Treatment Plan</label>
                        <textarea name="treatment" id="treatment" placeholder="Enter treatment plan, procedures, etc..." ></textarea>
                        <label for="prescription">Prescription</label>
                        <textarea name="prescription" id="prescription" placeholder="Enter medications, dosage, instructions..." ></textarea>
                        <label for="notes">Additional Notes</label>
                        <textarea name="notes" id="notes" placeholder="Any additional medical notes..." ></textarea>
                    </div>
                    
                    <div class="form-section">
                        <h4>Attachments</h4>
                        <label for="medical_file">Medical File (Optional)</label>
                        <input type="file" name="medical_file" id="medical_file" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png,.txt">
                        <div class="file-info">
                            Allowed File Types: PDF, DOC, DOCX, JPG, PNG, TXT (Max 5MB)
                        </div>
                    </div>
                    
                    <button type="submit">Generate Medical Record</button>
                </form>
            <?php endif; ?>
        </div>
    </div>
</body>
</html> 